# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_split_frequencies <- function(forest_object, max_depth) {
    .Call('_grftsls_compute_split_frequencies', PACKAGE = 'grftsls', forest_object, max_depth)
}

compute_weights <- function(forest_object, train_matrix, sparse_train_matrix, test_matrix, sparse_test_matrix, num_threads) {
    .Call('_grftsls_compute_weights', PACKAGE = 'grftsls', forest_object, train_matrix, sparse_train_matrix, test_matrix, sparse_test_matrix, num_threads)
}

compute_weights_oob <- function(forest_object, test_matrix, sparse_test_matrix, num_threads) {
    .Call('_grftsls_compute_weights_oob', PACKAGE = 'grftsls', forest_object, test_matrix, sparse_test_matrix, num_threads)
}

deserialize_tree <- function(forest_object, tree_index) {
    .Call('_grftsls_deserialize_tree', PACKAGE = 'grftsls', forest_object, tree_index)
}

merge <- function(forest_objects) {
    .Call('_grftsls_merge', PACKAGE = 'grftsls', forest_objects)
}

tsls_train <- function(train_matrix, sparse_train_matrix, outcome_index, treatment_index, input_instrument, sample_weight_index, use_sample_weights, mtry, num_trees, min_node_size, sample_fraction, honesty, honesty_fraction, ci_group_size, alpha, imbalance_penalty, clusters, samples_per_cluster, compute_oob_predictions, num_threads, seed) {
    .Call('_grftsls_tsls_train', PACKAGE = 'grftsls', train_matrix, sparse_train_matrix, outcome_index, treatment_index, input_instrument, sample_weight_index, use_sample_weights, mtry, num_trees, min_node_size, sample_fraction, honesty, honesty_fraction, ci_group_size, alpha, imbalance_penalty, clusters, samples_per_cluster, compute_oob_predictions, num_threads, seed)
}

tsls_predict <- function(forest_object, train_matrix, sparse_train_matrix, outcome_index, treatment_index, input_instrument, test_matrix, sparse_test_matrix, num_threads, estimate_variance) {
    .Call('_grftsls_tsls_predict', PACKAGE = 'grftsls', forest_object, train_matrix, sparse_train_matrix, outcome_index, treatment_index, input_instrument, test_matrix, sparse_test_matrix, num_threads, estimate_variance)
}

tsls_predict_oob <- function(forest_object, train_matrix, sparse_train_matrix, outcome_index, treatment_index, input_instrument, num_threads, estimate_variance) {
    .Call('_grftsls_tsls_predict_oob', PACKAGE = 'grftsls', forest_object, train_matrix, sparse_train_matrix, outcome_index, treatment_index, input_instrument, num_threads, estimate_variance)
}

test_tsls_prediction <- function() {
    .Call('_grftsls_test_tsls_prediction', PACKAGE = 'grftsls')
}

test_tsls_compute_variance <- function() {
    .Call('_grftsls_test_tsls_compute_variance', PACKAGE = 'grftsls')
}

test_tsls_relabeling <- function(samples, train_matrix, sparse_train_matrix, outcome_index, treatment_index, input_instrument) {
    .Call('_grftsls_test_tsls_relabeling', PACKAGE = 'grftsls', samples, train_matrix, sparse_train_matrix, outcome_index, treatment_index, input_instrument)
}

test_data <- function(samples, train_matrix, sparse_train_matrix, outcome_index, treatment_index, input_instrument, i) {
    .Call('_grftsls_test_data', PACKAGE = 'grftsls', samples, train_matrix, sparse_train_matrix, outcome_index, treatment_index, input_instrument, i)
}

